name: Run Tests

on: [push]

jobs:
  cabal:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cabal dir
      uses: actions/cache@v4
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-cabal-${{ hashFiles('*.cabal') }}
        restore-keys: ${{ runner.os }}-cabal-

    - run: cabal update 
    - run: cabal test
    - run: cabal install doctest
    - run: PATH=$HOME/.cabal/bin:$PATH cabal repl --with-ghc=doctest --ghc-options="-XQuasiQuotes -XOverloadedStrings"

  stackage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        resolver:
        - 'lts-10'
        - 'lts-11'
        - 'lts-12'
        - 'lts-13'
        - 'lts-14'
        - 'lts-15'
        - 'lts-16'
        - 'lts-17'
        - 'lts-18'
        - 'lts-19'
        - 'lts-20'
        - 'lts-21'
        - 'lts-22'

    steps:
    - uses: actions/checkout@v4
    - name: Cache stack dir
      uses: actions/cache@v4
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ matrix.resolver }}-${{ hashFiles('*.cabal') }}
        restore-keys: ${{ runner.os }}-stack-${{ matrix.resolver }}-

    - run: stack test --haddock --no-terminal --resolver ${{ matrix.resolver }}
